// vuejs/nutrition/src/components/NutritionForm.vue
<script>
import axios from 'axios'

export default {
    data() {
        return {
            recipes: [],
            isLoading: true,
            maxProtein: 0,
            minProtein: 0,
            maxFat: 0,
            minFat: 0,
            maxCarbs: 0,
            minCarbs: 0,
            maxCalories: 0,
            minCalories: 0,
            numberOfRecords: 0
        }
    },
    methods: {
        submit() {
            console.log("Submitted Form")
            var nutritionUrl = this.createUrl()
            axios
                .get(nutritionUrl)
                .then(response => (this.recipes = response.data))
                .then(this.isLoading = false)
        },
        createUrl() {
            var apiUrl = "https://api.spoonacular.com/recipes/findByNutrients?apiKey=8989350b92c448b890ada075143c8d0a"
            if (this.minProtein > 0) {
              apiUrl = apiUrl + "&minProtein=" + this.minProtein;
            }
            if (this.maxProtein > 0) {
              apiUrl = apiUrl + "&maxProtein=" + this.maxProtein;
            }
            if (this.minFat > 0) {
              apiUrl = apiUrl + "&minFat=" + this.minFat;
            }
            if (this.maxFat > 0) {
              apiUrl = apiUrl + "&maxFat=" + this.maxFat;
            }
            if (this.minCarbs > 0) {
              apiUrl = apiUrl + "&minCarbs=" + this.minCarbs;
            }
            if (this.maxCarbs > 0) {
              apiUrl = apiUrl + "&maxCarbs=" + this.maxCarbs;
            }
            if (this.minCalories > 0) {
              apiUrl = apiUrl + "&minCalories=" + this.minCalories;
            }
            if (this.maxCalories > 0) {
              apiUrl = apiUrl + "&maxCalories=" + this.maxCalories;
            }
            if (this.numberOfRecords > 0) {
              apiUrl = apiUrl + "&number=" + this.numberOfRecords;
            }
            else {
              apiUrl = apiUrl + "&number=10";
            }
            return apiUrl;
        }
    },
    mounted () {
        console.log("Mounting")
    }
}
</script>
    
<template>
    <h1>Nutrition Form</h1>

    <form>
        <label>Max Protein: </label>
        <input v-model="maxProtein">
        <br>
        <label>Min Protein: </label>
        <input v-model="minProtein">
        <br>
        <label>Max Fat: </label>
        <input v-model="maxFat">
        <br>
        <label>Min Fat: </label>
        <input v-model="minFat">
        <br>
        <label>Max Carbs: </label>
        <input v-model="maxCarbs">
        <br>
        <label>Min Carbs: </label>
        <input v-model="minCarbs">
        <br>
        <label>Max Calories: </label>
        <input v-model="maxCalories">
        <br>
        <label>Min Calories: </label>
        <input v-model="minCalories">
        <br>
        <label>Number of Records: </label>
        <input v-model="numberOfRecords">
        <br>
        <button type="button" @click="submit">Submit</button>
    </form>

    <table v-if="!isLoading">
        <thead>
            <tr>
                <td>Title</td>
                <td>Protein</td>
                <td>Fat</td>
                <td>Carbs</td>
                <td>Calories</td>
            </tr>
        </thead>
        <tbody>
            <tr v-for="(item, index) in recipes" :key="index">
                <td>{{ item.title }}</td>
                <td>{{ item.protein }}</td>
                <td>{{ item.fat }}</td>
                <td>{{ item.carbs }}</td>
                <td>{{ item.calories }}</td>
            </tr>
        </tbody>
    </table>
</template>

<style>
td {
    padding: 15px;
}
</style>

// react/nutrition/src/nutrition-form/nutrition-form.component.tsx
import React, { useState } from 'react';
import { Recipe } from './recipe.model';
import { Nutrition } from './nutrition-form.model';
import './nutrition-form.css'

const NutritionForm = () => {
    console.log("help");
    const [recipes, setRecipes] = useState<Recipe[]>([]);
    const [nutritionInput, setNutritionInput] = useState<Nutrition>({
      minProtein: 0,
      maxProtein: 0,
      minFat: 0,
      maxFat: 0,
      minCarbs: 0,
      maxCarbs: 0,
      minCalories: 0,
      maxCalories: 0,
      numberOfRecords: 0,
    });

    const handleChange = (event: any) => {
      var value = event.target.value;
      var name = event.target.name;
      setNutritionInput({
        ...nutritionInput, [name]: value
      });
    }

    const handleSubmit = (event: any) => {
      alert(nutritionInput.minProtein + nutritionInput.numberOfRecords);
    }

    const generateUrl = () => {
      var apiUrl: string = "https://api.spoonacular.com/recipes/findByNutrients?apiKey=8989350b92c448b890ada075143c8d0a" 
      if (nutritionInput.minProtein > 0) {
        apiUrl = apiUrl + "&minProtein=" + nutritionInput.minProtein;
      }
      if (nutritionInput.maxProtein > 0) {
        apiUrl = apiUrl + "&maxProtein=" + nutritionInput.maxProtein;
      }
      if (nutritionInput.minFat > 0) {
        apiUrl = apiUrl + "&minFat=" + nutritionInput.minFat;
      }
      if (nutritionInput.maxFat > 0) {
        apiUrl = apiUrl + "&maxFat=" + nutritionInput.maxFat;
      }
      if (nutritionInput.minCarbs > 0) {
        apiUrl = apiUrl + "&minCarbs=" + nutritionInput.minCarbs;
      }
      if (nutritionInput.maxCarbs > 0) {
        apiUrl = apiUrl + "&maxCarbs=" + nutritionInput.maxCarbs;
      }
      if (nutritionInput.minCalories > 0) {
        apiUrl = apiUrl + "&minCalories=" + nutritionInput.minCalories;
      }
      if (nutritionInput.maxCalories > 0) {
        apiUrl = apiUrl + "&maxCalories=" + nutritionInput.maxCalories;
      }
      if (nutritionInput.numberOfRecords > 0) {
        apiUrl = apiUrl + "&numberOfRecords=" + nutritionInput.numberOfRecords;
      }
      else {
        apiUrl = apiUrl + "&numberOfRecords=10";
      }
      return apiUrl;
    }

    return (
      <div className='container'>
        <form onSubmit={handleSubmit}>
          <label>Min Protein: </label>
            <input type="number" name="minProtein" onChange={handleChange}/><br/>
          <label>Max Protein: </label>
            <input type="number" name="maxProtein" onChange={handleChange}/><br/>
          <label>Min Fat: </label>
            <input type="number" name="minProtein" onChange={handleChange}/><br/>
          <label>Max Fat: </label>
            <input type="number" name="maxFat" onChange={handleChange}/><br/>
          <label>Min Carbs: </label>
            <input type="number" name="minCarbs" onChange={handleChange}/><br/>
          <label>Max Carbs: </label>
            <input type="number" name="maxCarbs" onChange={handleChange}/><br/>
          <label>Min Calories: </label>
            <input type="number" name="minCalories" onChange={handleChange}/><br/>
          <label>Max Calories: </label>
            <input type="number" name="maxCalories" onChange={handleChange}/><br/>
          <label>Number of Records: </label>
            <input type="number" name="numberOfRecords" onChange={handleChange}/><br/>
          <button type='submit' value="Submit">Submit</button>
        </form>
        <ul>
          {recipes.map(recipe => (
            <li>{recipe.title}</li>
          ))}
        </ul>
      </div>
    )
    
  
  }

  
export default NutritionForm;
